# Generated by Django 4.2 on 2026-01-13 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', help_text='Configuration name', max_length=100)),
                ('api_key', models.CharField(help_text='OpenAI API Key', max_length=255)),
                ('base_url', models.CharField(blank=True, help_text='Custom API base URL (e.g., https://api.openai.com/v1). Leave blank for default.', max_length=255, null=True)),
                ('model', models.CharField(default='gpt-4', help_text='Model name (e.g., gpt-4, gpt-3.5-turbo)', max_length=50)),
                ('temperature', models.FloatField(default=0.1, help_text='Temperature for generation (0.0-1.0)')),
                ('max_tokens', models.IntegerField(default=1000, help_text='Maximum tokens to generate')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'OpenAI Configuration',
                'verbose_name_plural': 'OpenAI Configurations',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
